/** Curated emoji set with simple keyword search, kept deliberately small
 * and classroom-appropriate rather than pulling in a full emoji library. */
export const EMOJI_CATEGORIES = [
  {
    name: "Smileys",
    emojis: [
      ["😀", "grinning happy smile"],
      ["😃", "grinning happy smile"],
      ["😄", "happy smile laugh"],
      ["😁", "grin happy smile"],
      ["😆", "laugh happy squint"],
      ["😅", "sweat laugh nervous"],
      ["🤣", "rofl laugh floor"],
      ["😂", "laugh cry joy tears"],
      ["🙂", "smile slight"],
      ["🙃", "upside down smile"],
      ["😉", "wink smile"],
      ["😊", "smile blush happy"],
      ["😇", "angel halo smile innocent"],
      ["🥰", "love smile hearts"],
      ["😍", "heart eyes love"],
      ["🤩", "star eyes excited"],
      ["😘", "kiss love"],
      ["😋", "yum tongue tasty"],
      ["😛", "tongue playful"],
      ["😜", "wink tongue silly"],
      ["🤪", "goofy silly crazy"],
      ["🤗", "hug smile"],
      ["🤔", "thinking hmm"],
      ["🤨", "skeptical eyebrow"],
      ["😐", "neutral face"],
      ["🙄", "eyeroll annoyed"],
      ["😏", "smirk sly"],
      ["😴", "sleep tired zzz"],
      ["🥱", "yawn tired"],
      ["😌", "relieved calm content"],
      ["😔", "sad pensive"],
      ["😢", "cry sad tear"],
      ["😭", "cry sob sad"],
      ["😤", "frustrated huff proud"],
      ["😠", "angry mad"],
      ["😡", "angry furious mad"],
      ["🥳", "party celebrate"],
      ["😱", "shocked scream"],
      ["😨", "fearful scared"],
      ["😰", "anxious worried sweat"],
      ["🤯", "mind blown shocked"],
      ["😳", "flushed embarrassed"],
      ["🥺", "pleading puppy eyes"],
      ["😷", "mask sick"],
    ],
  },
  {
    name: "Gestures",
    emojis: [
      ["👍", "thumbs up good yes"],
      ["👎", "thumbs down bad no"],
      ["👏", "clap applause"],
      ["🙌", "praise hands up celebrate"],
      ["🙏", "pray thanks please"],
      ["👋", "wave hello bye"],
      ["🤝", "handshake deal"],
      ["✋", "hand stop"],
      ["👌", "ok perfect"],
      ["🤞", "fingers crossed luck"],
      ["✌️", "peace victory"],
      ["🤟", "love you gesture"],
      ["🤘", "rock on"],
      ["👊", "fist bump punch"],
      ["✊", "fist power"],
      ["💪", "strong muscle flex"],
      ["👆", "point up"],
      ["👇", "point down"],
      ["👈", "point left"],
      ["👉", "point right"],
      ["🤙", "call me hang loose"],
      ["💃", "dance"],
      ["🕺", "dance"],
      ["🧠", "brain smart"],
      ["👀", "eyes looking"],
    ],
  },
  {
    name: "Hearts",
    emojis: [
      ["❤️", "love heart red"],
      ["🧡", "heart orange"],
      ["💛", "heart yellow"],
      ["💚", "heart green"],
      ["💙", "heart blue"],
      ["💜", "heart purple"],
      ["🖤", "heart black"],
      ["🤍", "heart white"],
      ["💔", "heartbroken sad"],
      ["💕", "hearts love two"],
      ["💓", "heart beating love"],
      ["💖", "heart sparkling love"],
      ["💯", "hundred perfect"],
      ["✨", "sparkles shine"],
      ["🔥", "fire lit hot great"],
      ["⭐", "star favorite"],
    ],
  },
  {
    name: "Celebration & study",
    emojis: [
      ["🎉", "party celebrate confetti"],
      ["🎊", "confetti party"],
      ["🎈", "balloon party"],
      ["🎁", "gift present"],
      ["🏆", "trophy win champion"],
      ["🥇", "gold medal first"],
      ["🎓", "graduation cap school"],
      ["📚", "books study"],
      ["✏️", "pencil write"],
      ["📝", "memo notes write"],
      ["✅", "check done yes"],
      ["❌", "x wrong no"],
      ["❗", "exclamation important"],
      ["❓", "question confused"],
      ["💡", "idea lightbulb"],
      ["📌", "pin important"],
      ["🎯", "target goal bullseye"],
    ],
  },
  {
    name: "Animals & food",
    emojis: [
      ["🐶", "dog puppy"],
      ["🐱", "cat kitten"],
      ["🐰", "rabbit bunny"],
      ["🦊", "fox"],
      ["🐻", "bear"],
      ["🐼", "panda"],
      ["🦁", "lion"],
      ["🦋", "butterfly"],
      ["☕", "coffee"],
      ["🍕", "pizza"],
      ["🍎", "apple fruit"],
      ["🍰", "cake dessert"],
      ["🍩", "donut"],
      ["🌮", "taco food"],
      ["☀️", "sun sunny weather"],
      ["🌈", "rainbow"],
      ["🌍", "earth world globe"],
    ],
  },
];
